/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ropes;

import java.io.File;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Urban
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */

    private int privMediaSelection;
    public MainWindow() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup_store_size_select = new javax.swing.ButtonGroup();
        buttonGroup_store_retrive = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_media = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton_allSpace = new javax.swing.JRadioButton();
        jRadioButton_partSpace = new javax.swing.JRadioButton();
        jSlider_size_select = new javax.swing.JSlider();
        jRadioButton_store = new javax.swing.JRadioButton();
        jRadioButton_retrive = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_files = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton_setPath = new javax.swing.JButton();
        jLabel_slider_value = new javax.swing.JLabel();
        jButton_clear_fileList = new javax.swing.JButton();
        jPasswordField_master_password = new javax.swing.JPasswordField();
        jCheckBox_showPassword = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ropes - Robust Offline Physical Encrypted Storage");
        setName("MainWindow"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Master Password");

        jComboBox_media.setName("select_media_cmb"); // NOI18N
        jComboBox_media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_mediaActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Media");
        jLabel1.setName(""); // NOI18N

        buttonGroup_store_size_select.add(jRadioButton_allSpace);
        jRadioButton_allSpace.setSelected(true);
        jRadioButton_allSpace.setText("Fill all avalible space");
        jRadioButton_allSpace.setName("all_space_radio"); // NOI18N
        jRadioButton_allSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_allSpaceActionPerformed(evt);
            }
        });

        buttonGroup_store_size_select.add(jRadioButton_partSpace);
        jRadioButton_partSpace.setText("Set storage space");
        jRadioButton_partSpace.setMaximumSize(new java.awt.Dimension(121, 23));
        jRadioButton_partSpace.setName("some_space_radio"); // NOI18N
        jRadioButton_partSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_partSpaceActionPerformed(evt);
            }
        });

        jSlider_size_select.setMajorTickSpacing(100);
        jSlider_size_select.setMaximum(1000);
        jSlider_size_select.setMinorTickSpacing(10);
        jSlider_size_select.setPaintTicks(true);
        jSlider_size_select.setToolTipText("");
        jSlider_size_select.setValue(0);
        jSlider_size_select.setEnabled(false);
        jSlider_size_select.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_size_selectStateChanged(evt);
            }
        });

        buttonGroup_store_retrive.add(jRadioButton_store);
        jRadioButton_store.setSelected(true);
        jRadioButton_store.setText("store");

        buttonGroup_store_retrive.add(jRadioButton_retrive);
        jRadioButton_retrive.setText("retrive");

        jButton2.setText("write");

        jScrollPane1.setViewportView(jList_files);

        jLabel3.setText("Files for storage");

        jButton3.setText("Add file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_setPath.setText("Set path");
        jButton_setPath.setEnabled(false);

        jLabel_slider_value.setEnabled(false);

        jButton_clear_fileList.setText("Clear");

        jPasswordField_master_password.setEchoChar('*');

        jCheckBox_showPassword.setText("Show Password");
        jCheckBox_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_allSpace)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_clear_fileList))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_partSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider_size_select, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jRadioButton_store)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_retrive)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_setPath))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_showPassword)
                                    .addComponent(jPasswordField_master_password, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_slider_value)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_store)
                    .addComponent(jRadioButton_retrive))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_setPath))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField_master_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_showPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton_clear_fileList))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_allSpace)
                .addGap(17, 17, 17)
                .addComponent(jLabel_slider_value)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider_size_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_partSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       final JFileChooser fc = new JFileChooser();
       fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
       fc.setMultiSelectionEnabled(true);
       
       int returnVal = fc.showOpenDialog(MainWindow.this);      
       if (returnVal == JFileChooser.APPROVE_OPTION) {
           File file = fc.getSelectedFile();
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         System.exit(0);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               SystemInfo info = new SystemInfo();
               Map drives = info.getMediaDrives();
               Iterator it = drives.entrySet().iterator();
               while(it.hasNext()){
                   Map.Entry pairs = (Map.Entry)it.next();
                   SystemInfo.MediaInfo mi = (SystemInfo.MediaInfo)pairs.getValue();                  
                   jComboBox_media.addItem(pairs.getKey() + "  -  " + mi.description);
                   it.remove();
                  
               }
                //disable the setPath button, untill media is selected
                jButton_setPath.setEnabled(false);               
                
               
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox_mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_mediaActionPerformed
      //enables the button after firs time media is selected
      jButton_setPath.setEnabled(true);
       //reset controlls
      jSlider_size_select.setValue(0);
      jLabel_slider_value.setText("0 Mb");
  
      SystemInfo info = new SystemInfo();
      //TODO make drives global var
      Map drives = info.getMediaDrives();    
      //gets the string of the meda drivev selected
      String selected = jComboBox_media.getSelectedItem().toString().split("-")[0].replaceAll("\\s+","");
      
      Integer maxSize = ((SystemInfo.MediaInfo)drives.get(selected)).freeSpace;
      
      jSlider_size_select.setMaximum(maxSize);
      

      
      //Create the label table
      Hashtable labelTable = new Hashtable();
      labelTable.put( new Integer( 0 ), new JLabel("0 Mb") );
      labelTable.put( new Integer( maxSize ), new JLabel(String.valueOf(maxSize) + " Mb") );
      jSlider_size_select.setLabelTable( labelTable );
      jSlider_size_select.setPaintLabels(true);
    
      //remeber last select
      privMediaSelection = jComboBox_media.getSelectedIndex();
    }//GEN-LAST:event_jComboBox_mediaActionPerformed

    private void jRadioButton_partSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_partSpaceActionPerformed
        jSlider_size_select.setEnabled(true);
        jLabel_slider_value.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_partSpaceActionPerformed

    private void jRadioButton_allSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_allSpaceActionPerformed
        jSlider_size_select.setEnabled(false);
        jLabel_slider_value.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton_allSpaceActionPerformed

    private void jSlider_size_selectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_size_selectStateChanged
        jLabel_slider_value.setText(String.valueOf(jSlider_size_select.getValue()) + " Mb");
    }//GEN-LAST:event_jSlider_size_selectStateChanged

    private void jCheckBox_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_showPasswordActionPerformed
           if(jCheckBox_showPassword.isSelected()){
               jPasswordField_master_password.setEchoChar((char)0);
           }else{
               jPasswordField_master_password.setEchoChar('*');
           }
    }//GEN-LAST:event_jCheckBox_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_store_retrive;
    private javax.swing.ButtonGroup buttonGroup_store_size_select;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_clear_fileList;
    private javax.swing.JButton jButton_setPath;
    private javax.swing.JCheckBox jCheckBox_showPassword;
    private javax.swing.JComboBox jComboBox_media;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_slider_value;
    private javax.swing.JList jList_files;
    private javax.swing.JPasswordField jPasswordField_master_password;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton_allSpace;
    private javax.swing.JRadioButton jRadioButton_partSpace;
    private javax.swing.JRadioButton jRadioButton_retrive;
    private javax.swing.JRadioButton jRadioButton_store;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider_size_select;
    // End of variables declaration//GEN-END:variables
}
